africapolis_countries = {
    'Algeria': 'Algeriet',
    'Angola': 'Angola',
    'Benin': 'Benin',
    'Botswana': 'Botswana',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cameroon': 'Kamerun',
    'Central African Republic': 'Centralafrikanska republiken',
    'Chad': 'Tchad',
    'Djibouti': 'Djibouti',
    'Egypt': 'Egypten',
    'Equatorial Guinea': 'Ekvatorialguinea',
    'Eritrea': 'Eritrea',
    'Ethiopia': 'Etiopien',
    'Gabon': 'Gabon',
    'Ghana': 'Ghana',
    'Guinea': 'Guinea',
    'Guinea-Bissau': 'Guinea Bissau',
    'Kenya': 'Kenya',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Libya': 'Libyen',
    'Malawi': 'Malawi',
    'Mali': 'Mali',
    'Mauritania': 'Mauretanien',
    'Morocco': 'Marocko',
    'Mozambique': 'Moçambique',
    'Namibia': 'Namibia',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'Rwanda': 'Rwanda',
    'Sao Tome and Principe': 'São Tomé och Príncipe',
    'Senegal': 'Senegal',
    'Sierra Leone': 'Sierra Leone',
    'Somalia': 'Somalia',
    'South Africa': 'Sydafrika',
    'South Sudan': 'Sydsudan',
    'Sudan': 'Sudan',
    'Tanzania': 'Tanzania',
    'Togo': 'Togo',
    'Tunisia': 'Tunisien',
    'Uganda': 'Uganda',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe',
    'Cabo Verde': 'Kap Verde',
    'Democratic Republic of the Congo': 'Demokratiska republiken Kongo',
    'Republic of the Congo': 'Kongo-Brazzaville',
    'Cote d`Ivoire': 'Elfenbenskusten',
    'The Gambia': 'Gambia',
    'Kingdom of Eswatini': 'Swaziland'}